@ cdecl hipDestroyExternalMemory(ptr)
@ cdecl hipDeviceSynchronize()
@ cdecl hipDriverGetVersion(ptr)
@ cdecl hipEventCreate(ptr)
@ cdecl hipEventCreateWithFlags(ptr long)
@ cdecl hipEventElapsedTime(ptr ptr ptr)
@ cdecl hipEventQuery(ptr)
@ cdecl hipEventRecord(ptr ptr)
@ cdecl hipEventSynchronize(ptr)
@ cdecl hipExternalMemoryGetMappedBuffer(ptr ptr ptr)
@ cdecl hipFree(ptr)
@ cdecl hipGetDeviceCount(ptr)
@ cdecl hipGetDevicePropertiesR0600(ptr long)
@ cdecl hipGetErrorString(long)
@ cdecl hipGetLastError()
@ cdecl hipImportExternalMemory(ptr ptr)
@ cdecl hipLaunchKernel(ptr ptr ptr ptr long ptr)
@ cdecl hipMalloc(ptr long)
@ cdecl hipMemcpyAsync(ptr ptr long long ptr)
@ cdecl hipMemcpy(ptr ptr long long)
@ cdecl hipMemcpyToSymbol(ptr ptr long long long)
@ cdecl hipMemsetAsync(ptr long long ptr)
@ cdecl hipMemset(ptr long long)
@ cdecl __hipPopCallConfiguration(ptr ptr ptr ptr)
@ cdecl __hipPushCallConfiguration(ptr ptr long ptr)
@ cdecl __hipRegisterFatBinary(ptr)
@ cdecl __hipRegisterFunction(ptr ptr ptr ptr long ptr ptr ptr ptr ptr)
@ cdecl __hipRegisterVar(ptr ptr ptr)
@ cdecl hipRuntimeGetVersion(ptr)
@ cdecl hipSetDevice(long)
@ cdecl hipStreamCreateWithFlags(ptr long)
@ cdecl hipStreamSynchronize(ptr)
@ cdecl __hipUnregisterFatBinary(ptr)
